<?php

namespace UPOND\OrthophonieBundle\Repository;

/**
 * MultimediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MultimediaRepository extends \Doctrine\ORM\EntityRepository
{
    public function get7MultimediaAleatoire($strategie)
    {

        $em = $this
            ->getEntityManager();
        $queryMultimedia = $em->createQuery(
            'SELECT m
            FROM UPONDOrthophonieBundle:Multimedia m
            JOIN m.strategie s
            WHERE s = :strategie'
        );
        $queryMultimedia->setParameter('strategie', $strategie);

        $multimedias = $queryMultimedia->getResult();

        // on prend un id aléatoire parmi les résultats
        $tabIdMultimedia = array_rand($multimedias, 7);
        $arrayMultimedia = array();
        foreach($tabIdMultimedia as $element)
        {
            $arrayMultimedia[] = $multimedias[$element];
        }

        // on récupere l'entité de l'ID
        $queryMultimedia = $em->createQuery(
            'SELECT m
            FROM UPONDOrthophonieBundle:Multimedia m
            WHERE m.idMultimedia IN (:arrayMultimedia)'
        );
        $queryMultimedia->setParameter('arrayMultimedia', $arrayMultimedia);
        $listRandomMultimedia = $queryMultimedia->getResult();

        return $listRandomMultimedia;
    }

    public function getIdMultimediaFromPartieAndPhase($partie, $phase)
    {
        $em = $this
            ->getEntityManager();
        $queryMultimedia = $em->createQuery(
            'SELECT m.idMultimedia
            FROM UPONDOrthophonieBundle:Exercice e
            JOIN e.etapes et
            JOIN et.multimedias m
            WHERE e.partie = :partie AND e.phase = :phase
            GROUP BY m.idMultimedia'
        );
        $queryMultimedia->setParameters(array('partie' => $partie,
            'phase' => $phase));

        $idMultimedia = $queryMultimedia->getResult();
        
        return $idMultimedia;
    }

    public function getMultimediaInArrayOfIdMultimedia($arrayMultimedia)
    {

        $em = $this
            ->getEntityManager();
        // on récupere l'entité de l'ID
        $queryMultimedias = $em->createQuery(
            'SELECT m
                FROM UPONDOrthophonieBundle:Multimedia m
                WHERE m.idMultimedia IN (:arrayIdMultimedias)'
        );
        $queryMultimedias->setParameter('arrayIdMultimedias', $arrayMultimedia);
        $listMultimedias = $queryMultimedias->getResult();
        return $listMultimedias;
    }

    public function getMultimediaNotInArrayOfIdMultimedia($arrayMultimedia)
    {

        $em = $this
            ->getEntityManager();
        // on récupere l'entité de l'ID
        $queryMultimedias = $em->createQuery(
            'SELECT m
                FROM UPONDOrthophonieBundle:Multimedia m
                WHERE m.idMultimedia NOT IN (:arrayIdMultimedias)'
        );
        $queryMultimedias->setParameter('arrayIdMultimedias', $arrayMultimedia);
        $listMultimedias = $queryMultimedias->getResult();
        return $listMultimedias;
    }

    public function getMultimediasInEtapes($etapes)
    {
        $em = $this
            ->getEntityManager();
        $queryMultimedia = $em->createQuery(
            'SELECT m
                FROM UPONDOrthophonieBundle:Multimedia m
                JOIN m.etapes e
                WHERE e IN (:etapes)'
        );
        $queryMultimedia->setParameters(array('etapes' => $etapes));

        $multimedias = $queryMultimedia->getResult();

        return $multimedias;
    }
}
