<?php

namespace UPOND\OrthophonieBundle\Repository;

/**
 * StrategieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StrategieRepository extends \Doctrine\ORM\EntityRepository
{
}
