<?php

namespace UPOND\OrthophonieBundle\Repository;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends \Doctrine\ORM\EntityRepository
{
    public function findIdByNomEtPrenom($nom, $prenom)
    {
        $em = $this
            ->getEntityManager();
        // on récupere l'entité de l'ID
        $query = $em->createQuery(
            "SELECT u.id
                FROM UPONDOrthophonieBundle:Utilisateur u
                WHERE u.nom = :nom AND u.prenom = :prenom"
        );
        $query->setParameter('nom', $nom);
        $query->setParameter('Prenom',$prenom);
        $utilisateur = $query->getOneOrNullResult();
        return $utilisateur;
    }
}
